---
apiVersion: v1
kind: Service
metadata:
  name: k8s-ext-conn-validator-svc
  labels:
    app: k8s-ext-conn-validator
    tier: backend
    environment: dev
spec:
  type: ClusterIP
  selector:
    app: k8s-ext-conn-validator
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-ext-conn-validator
spec:
  selector:
    matchLabels:
      app: k8s-ext-conn-validator
  replicas: 1
  template:
    metadata:
      labels:
        app: k8s-ext-conn-validator
    spec:
      containers:
      - name: k8s-ext-conn-validator
        image: vokdevops/utils/k8s-ext-conn-validator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: DB_PASS
            value: <password>
          - name: DB_URL
            value: <db-url>
          - name: DB_USER
            value: <user-name>
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1